### ISSUE TITLE
✨ Feature: 프로젝트 개발 환경 구축

### ISSUE THREAD

**Issue by ahnsugyeong** [Team-Zzangdol/mooDoodle-backend#1]
## 🔎 Description
> 프로젝트 개발 환경을 구축합니다.

## ✔️ To-do
- [x] .gitignore 작성
- [x] 멀티 모듈 프로젝트 구성
- [x] API 응답 포맷 작성
- [x] Exception Handler 작성
