### ISSUE TITLE
✨ Feature: 이메일 인증번호 전송 및 검증 API 구현

### ISSUE THREAD

**Issue by ahnsugyeong** [Team-Zzangdol/mooDoodle-backend#17]
### 1️⃣ 이메일 인증번호 전송 API
1. AWS SES를 활용하여 6자리 인증번호를 전송합니다. (유효 시간: 5분)
2. Redis에 인증번호를 저장합니다.

### 2️⃣ 이메일 인증번호 검증 API
1. 사용자로부터 받은 인증번호와 Redis의 인증번호를 비교합니다.
2. 인증번호가 일치하고, 만료 시간이 지나지 않았다면 인증을 성공으로 처리합니다.

## ✔️ To-do
- [x] ElastiCache 설정
- [x] 이메일 인증번호 전송 API 구현
- [x] @RedisHash 사용해서 VerifiactionCode 저장
- [x] 인증번호 검증 API 구현
