### ISSUE TITLE
✨ Feature: CI/CD 파이프라인 구축

### ISSUE THREAD

**Issue by ahnsugyeong** [Team-Zzangdol/mooDoodle-backend#3]
## 🔎 Description
> CI/CD 파이프라인을 구축합니다.

### ☁️ API Server Architecture

<table>
  <tr>
    <td width="50%"><b>CI/CD</b></td>
    <td width="50%"><b>VPC</b></td>
  </tr>
  <tr>
    <td width="50%" style="background-color: white;"><img src="https://github.com/Team-Zzangdol/mooDoodle-backend/assets/88311377/9aae2199-30da-4d71-9156-0cf3930d053d"></td>
    <td width="50%"><img src="https://github.com/Team-Zzangdol/mooDoodle-backend/assets/88311377/a66d5c0b-2a15-467f-a8e5-48b2bd95e6df"></td>
  </tr>
</table>

### 📌 Profile
- 프로젝트는 local, dev, prod 세 가지 환경 프로파일로 구성될 예정이며, 각 환경별로 다른 포트 번호(local: 8081, dev: 8082, prod: 8083)를 사용할 것입니다.
- Nginx를 활용하여 리버스 프록시 설정을 통해 트래픽을 관리합니다.
- 이 이슈에서는 `local` 및 `dev` 환경을 구축할 예정입니다.

### 💡 Jib
`Jib`는 Dockerfile이 없거나 Docker가 설치되지 않은 상태에서도 `Java 애플리케이션용 Docker 이미지`를 빌드할 수 있게 해주는 도구입니다. 
애플리케이션을 `별개의 레이어`로 구성하고 `Docker 이미지 레이어 캐싱`을 활용하여 변경사항만 다시 빌드함으로써 빌드를 빠르게 유지할 수 있습니다.
따라서 이를 프로젝트 빌드 과정에 통합하여 사용하고자 합니다.

**🐳 Docker build flow**
![docker_build_flow](https://github.com/Team-Zzangdol/mooDoodle-backend/assets/88311377/39ec1b24-82d3-4dbe-b9e2-ad25d3aacd6d)

**✨ Jib build flow**
![jib_build_flow](https://github.com/Team-Zzangdol/mooDoodle-backend/assets/88311377/a58c22ea-0464-4e74-b97b-bda7c76b8314)

## ✔️ To-do
- [x] Docker 이미지 생성을 위한 Jib 설정
- [x] Dockerrun.aws.json 작성
- [x] .ebextensions 작성
- [x] nginx proxy 설정
- [x] 환경별 port 번호 설정
- [x] CI/CD 워크플로우 스크립트 작성
