### ISSUE TITLE
⚙️ Setting: Flyway 설정

### ISSUE THREAD

**Issue by ahnsugyeong** [Team-Zzangdol/mooDoodle-backend#48]
## 🔎 Description
> 효율적인 DB 형상 관리를 위해 `Flyway`를 도입합니다.

## ✔️ To-do
- [ ] Flyway 의존성 추가
- [ ] application.yml 설정
- [ ] flyway 스크립트 작성
