### ISSUE TITLE
✨ Feature: Submodule을 이용한 설정 파일 구성

### ISSUE THREAD

**Issue by ahnsugyeong** [Team-Zzangdol/mooDoodle-backend#5]
## 🔎 Description
> 프로젝트의 설정 파일(application.yml 등)을 중앙화된 방식으로 관리하기 위해, 별도의 private GitHub repository에 이를 저장하고 이를 `Submodule`로 프로젝트에 통합합니다.

## ✔️ To-do
- [x] 설정 파일 repository를 Submodule로 추가
- [x] .gitignore에 설정 파일 추가
- [x] gradle 스크립트에 copyYML task 추가
- [x] CI/CD 파이프라인 스크립트 수정
