### ISSUE TITLE
✨ Feature: 스크랩 기능 구현

### ISSUE THREAD

**Issue by ahnsugyeong** [Team-Zzangdol/mooDoodle-backend#70]
## 🔎 Description
> 스크랩 기능을 구현합니다.

## ✔️ To-do
- [x]  카테고리 생성 API 구현
- [x]  카테고리 목록 조회 API 구현
- [x]  스크랩 생성 기능 구현
- [x]  스크랩 카테고리 추가 API 구현
- [x]  스크랩 삭제 기능 구현
- [x]  [바텀시트] 카테고리 목록 조회 API 구현
- [x]  [스크랩 탭] 카테고리 목록 조회 API 구현
- [x]  빈 카테고리 더미데이터 상수 설정
- [x]  스크랩 ID 조회 기능 및 유효성 검증 로직 추가
- [x]  스크랩 카테고리에 속한 일기 목록 조회 API 구현
- [x]  일기 단건 조회 API에 요일 및 스크랩 여부 필드 추가
