### ISSUE TITLE
✨ Feature: 기본 카테고리 로직 구현

### ISSUE THREAD

**Issue by ahnsugyeong** [Team-Zzangdol/mooDoodle-backend#79]
## 🔎 Description
> 기본 카테고리(모든 스크랩) 로직을 구현합니다.

## ✔️ To-do
- [x] 회원가입 시 기본 카테고리 생성
- [x] 스크랩 생성 시 기본 카테고리에 추가
- [x] [바텀시트] 스크랩 카테고리 목록 조회 API에서 기본 카테고리 제외
